name: Deploy to Azure and Access Google Calendar

on:
  push:
    branches:
      - main

jobs:
  access-google-calendar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust as needed

      - name: Install dependencies
        run: npm install

      - name: Set up Google Cloud credentials
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}  # Pass secret as environment variable
        run: |
          echo "Google Cloud credentials are set as an environment variable"
          node server.js  # Replace with your JavaScript file name

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Azure Service Principal credentials

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: <YOUR_AZURE_APP_NAME>  # Replace with your Azure Web App name
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: .
